name: Update README
on:
  push:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:

jobs:
  readme:
    name: "Update README"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "test.README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: Wim Wenigerkind
          commit_user_email: wim.wenigerkind@heptacom.de
          commit_author: Wim Wenigerkind <wim.wenigerkind@heptacom.de>